export const newFacilities = [
  {
    id : 1,
    facility_name : 'Kuningan Room',
    location : 'Kuningan',
    capacity: 20,
    floor: 'Mega Kuningan',
    created_by: 'Hoho',
    room_number: 'Kuning',
    coords: [-100,  100],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
  {
    id : 6,
    facility_name : 'Maja Room',
    location : 'Maja',
    capacity: 20,
    floor: 'Mega Maja',
    created_by: 'Hihi',
    room_number: 'Majapahit',
    coords: [-155,  155],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
  {
    id : 2,
    facility_name : 'Bali Room',
    location : 'Bali',
    capacity: 20,
    floor: 'Mega Bali',
    created_by: 'Hoho',
    room_number: 'Baliness',
    coords: [-120,  150],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
  {
    id : 3,
    facility_name : 'Plaza Room',
    location : 'Plaza',
    capacity: 20,
    floor: 'Mega Plaza',
    created_by: 'Hoho',
    room_number: 'Plaza',
    coords: [-140,  155],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
  {
    id : 4,
    facility_name : 'Senayan Room',
    location : 'Senayan',
    capacity: 20,
    floor: 'Mega Senayan',
    created_by: 'Hoho',
    room_number: 'Senayan city',
    coords: [-145,  50],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
  {
    id : 5,
    facility_name : 'Serang Room',
    location : 'Serang',
    capacity: 20,
    floor: 'Mega Serang',
    created_by: 'Hoho',
    room_number: 'Serang',
    coords: [-75,  200],
    status: 'Not Booked',
    size: [64, 64],
    animation: null //'pulse'
  },
]